owner: ber1yo
repo: ut

sites:
  - name: HKUST
    url: https://hkust.edu.hk
    type: globalping
    location: china
  - name: HKUST Digital Humanities Initiative
    url: https://digitalhumanities.hkust.edu.hk/
    type: globalping
    location: china
  - name: HKUST Rare & Special e-Zone
    url: https://lbezone.hkust.edu.hk/
    type: globalping
    location: china
  - name: HKUST Library
    url: https://lbxibo.ust.hk/
    type: globalping
    location: china
  - name: HKUST Business School
    url: https://bm.hkust.edu.hk
    type: globalping
    location: china

status-website:
  theme: dark
  cname: ut.uh.work.gd
  # baseUrl: /ut
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: UT
  introTitle: 
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: DNSExit
      href: https://dnsexit.com/Direct.sv?cmd=userDNSList
